# Generated by Django 5.2 on 2026-06-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('term', models.CharField(choices=[('1', '1-chorak'), ('2', '2-chorak'), ('3', '3-chorak'), ('4', '4-chorak')], max_length=1)),
                ('academic_year', models.CharField(max_length=9)),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='GradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name_plural': 'grade categories',
                'db_table': 'grade_categories',
            },
        ),
        migrations.CreateModel(
            name='TermReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=1)),
                ('academic_year', models.CharField(max_length=9)),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_letter', models.CharField(max_length=2)),
                ('teacher_comment', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'term_reports',
            },
        ),
    ]
