# Generated by Django 5.2 on 2026-06-07 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.subject'),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.teacher'),
        ),
        migrations.AddField(
            model_name='grade',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grades.gradecategory'),
        ),
        migrations.AddField(
            model_name='termreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='termreport',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='termreport',
            unique_together={('student', 'subject', 'term', 'academic_year')},
        ),
    ]
