# Generated by Django 5.2 on 2026-06-07 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('monthly', 'Oylik'), ('yearly', 'Yillik'), ('once', 'Bir martalik')], max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fee_types',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('click', 'Click'), ('payme', 'Payme'), ('uzum', 'Uzum Bank'), ('transfer', "Bank o'tkazmasi")], max_length=15)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField()),
                ('received_by', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('overdue', "Muddati o'tgan"), ('cancelled', 'Bekor qilingan')], default='pending', max_length=15)),
                ('month', models.CharField(blank=True, max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.feetype')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
    ]
